baseURL = "/"
languageCode = "en-us"
title = "ryan.c"
theme = "hyde"
relativeURLs = true
author = "Ryan Campbell"
disqusShortname = "ryan-c"
googleAnalytics = "UA-18183842-4"
enableEmoji = true

[params]
  description = "I believe writing is a hobby worth persuing, so I share my thoughts here."
  copyright = " "
  themeColor = "theme-base-0r"
  latestpostcount = 3

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Posts"
    title = "Posts"
    url = "/blog/"
    weight = -110

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/"
    weight = -110

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    title = "Contact"
    url = "/contact/"
    weight = -110


