[build]
  command = "hugo;"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.57.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.57.2"

[[redirects]]
from = "https://ryancampbell.blog/automating-workspaces-on-macos/"
to = "https://bellrise.farm/house/automating-workspaces-on-macos/"
status = 301
force = true

[[redirects]]
from = "https://ryancampbell.blog/blog/automating-workspaces-on-macos/"
to = "https://bellrise.farm/house/automating-workspaces-on-macos/"
status = 301
force = true